### ISSUE TITLE
lucky_block should not depend on other mods

### ISSUE THREAD

**Issue by taikedz** [tenplus1/lucky_block#2]
Can I suggest making `lucky_blocks` more engine/framework-like and allowing other mods to register a callback to it like

    local schemdata = readschem()
    lucky_blocks.register("sch",schemdata,4)

or

    lucky_blocks.register("dro","ethereal:crystal_spike",1)

without providing them in Lucky itself ...?

(feedback on https://github.com/tenplus1/mobs_redo/issues/30)

**Comment by tenplus1** [comment]
look at the api.txt file that comes with lucky_blocks, it shows you how to make your own blocks for a mod and until then I will include a default set for specific mods.
