### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by SnarkBoojum** [tenplus1/lucky_block#3]
Hi

I would like to package this mod for Debian, but I would need proper releases to do so : can you please tag them? (plural = now and later on)

Thanks,

**Comment by tenplus1** [comment]
Tag them how ? explain please...

**Comment by tenplus1** [comment]
added 0.8 tags

**Comment by SnarkBoojum** [comment]
You forgot the "git push --tags" step : you have the tag in your local clone, but didn't make it public. :-)

**Comment by SnarkBoojum** [comment]
Could you push the tag, please?
